### ISSUE TITLE
Support Middleman 4.0

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/franklin#6]
This currently won't work on middleman 4.0. Fixes would include:

Using the config syntax: `set :source, 'source'` => `config[:source] = 'source'`
Fixing these issues:

```
`+': can't convert Middleman::CoreExtensions::Collections::LazyCollectorStep to String
```

```
config.rb:22:in `block in evaluate_configuration!': undefined method `start_with?'
```

Whatever other issues we find.

**Comment by jaredmorgs** [comment]
Yeah, I came across these today as well.

I was getting a mixture of errors that I thought were related to me getting AsciiDoc support into the templates (which I can do a PR for if you like).

I was also getting a middleman-core binstub error as well from bundle.

**Comment by jaredmorgs** [comment]
https://github.com/bryanbraun/franklin/pull/11 may resolve this. I'm going to see if I can pull it down locally and test on my docs site.

**Comment by bryanbraun** [comment]
Thanks @jaredmorgs. It's a big change, so the more eyes on it, the better!

**Comment by bryanbraun** [comment]
Did a bunch of testing and it looks great to me. Merging!
